import { Providers } from "@/providers/provider";
import ReduxProvider from "@/providers/redux-provider"; // Static import
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Focusly - Time Management and Focus Tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <Providers>
                    <ReduxProvider>{children}</ReduxProvider>
                </Providers>
            </body>
        </html>
    );
}
